# Generated by Django 2.2.2 on 2019-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('customer', 'customer'), ('executor', 'executor')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
